import { NextRequest, NextResponse } from "next/server";
import fs from "node:fs";
import path from "node:path";
import { Readable } from "node:stream";

const MEDIA_DIR = process.env.ALBUM_MEDIA_DIR;

const CONTENT_TYPES: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".mp4": "video/mp4",
};

// Filenames are always {16 hex chars}.{jpg|mp4}, generated by scripts/ingest-album.mjs.
const FILENAME_PATTERN = /^[a-f0-9]{16}\.(jpg|mp4)$/;

export async function GET(req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  if (!MEDIA_DIR) {
    return new NextResponse("Media directory not configured", { status: 500 });
  }

  const { path: segments } = await params;
  const [bucket, filename] = segments;

  if ((bucket !== "full" && bucket !== "thumb") || !filename || !FILENAME_PATTERN.test(filename)) {
    return new NextResponse("Not found", { status: 404 });
  }

  const filePath = path.join(MEDIA_DIR, bucket, filename);

  let stat: fs.Stats;
  try {
    stat = fs.statSync(filePath);
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }

  const contentType = CONTENT_TYPES[path.extname(filename)] ?? "application/octet-stream";
  const range = req.headers.get("range");
  const rangeMatch = range ? /bytes=(\d+)-(\d*)/.exec(range) : null;

  if (rangeMatch) {
    const start = Number(rangeMatch[1]);
    const end = rangeMatch[2] ? Number(rangeMatch[2]) : stat.size - 1;
    const stream = fs.createReadStream(filePath, { start, end });

    return new NextResponse(Readable.toWeb(stream) as unknown as ReadableStream, {
      status: 206,
      headers: {
        "Content-Type": contentType,
        "Content-Length": String(end - start + 1),
        "Content-Range": `bytes ${start}-${end}/${stat.size}`,
        "Accept-Ranges": "bytes",
        "Cache-Control": "public, max-age=31536000, immutable",
      },
    });
  }

  const stream = fs.createReadStream(filePath);
  return new NextResponse(Readable.toWeb(stream) as unknown as ReadableStream, {
    status: 200,
    headers: {
      "Content-Type": contentType,
      "Content-Length": String(stat.size),
      "Accept-Ranges": "bytes",
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
